plugins {
    id 'java'
    id("io.qameta.allure") version "4.2.0"
}

group = 'com.matuation'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    testImplementation 'org.assertj:assertj-core:3.27.7'
    testCompileOnly 'org.projectlombok:lombok:1.18.46'
    testAnnotationProcessor 'org.projectlombok:lombok:1.18.46'
    testImplementation 'tools.jackson.core:jackson-databind:3.2.2'
    compileOnly 'org.projectlombok:lombok:1.18.30'
    annotationProcessor 'org.projectlombok:lombok:1.18.30'
    testImplementation 'org.aeonbits.owner:owner:1.0.12'
    testImplementation 'net.datafaker:datafaker:2.7.0'
    testImplementation 'org.postgresql:postgresql:42.7.13'
    testImplementation 'io.rest-assured:rest-assured:6.0.0'
    testImplementation 'org.awaitility:awaitility:4.3.0'
}

test {
    useJUnitPlatform()
}

tasks.withType(JavaExec) {
    // Sets the default file encoding to UTF-8
    jvmArgs += '-Dfile.encoding=UTF-8'

    // Ensures standard output and error streams respect UTF-8 (Required for Java 18+)
    jvmArgs += '-Dstdout.encoding=UTF-8'
    jvmArgs += '-Dstderr.encoding=UTF-8'
}


